"""recruiter model

Revision ID: 01001d2121fa
Revises: da801df0736f
Create Date: 2025-11-30 15:05:41.774362

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01001d2121fa"
down_revision: Union[str, None] = "da801df0736f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recruiters",
        sa.Column("company", sa.String(length=100), nullable=False),
        sa.Column("postition", sa.String(length=100), nullable=False),
        sa.Column("surname", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("patronymic", sa.String(length=100), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("candidates", sa.Column("phone", sa.String(length=20), nullable=True))
    op.add_column(
        "candidates",
        sa.Column("location", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "candidates",
        sa.Column("surname", sa.String(length=100), nullable=False),
    )
    op.add_column(
        "candidates", sa.Column("name", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "candidates",
        sa.Column("patronymic", sa.String(length=100), nullable=True),
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=254),
        existing_nullable=False,
    )
    op.drop_column("users", "name")
    op.drop_column("users", "patronymic")
    op.drop_column("users", "surname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "surname",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "patronymic",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=254),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("candidates", "patronymic")
    op.drop_column("candidates", "name")
    op.drop_column("candidates", "surname")
    op.drop_column("candidates", "location")
    op.drop_column("candidates", "phone")
    op.drop_table("recruiters")
    # ### end Alembic commands ###
