"""edited candidate model

Revision ID: d2e9865e0059
Revises: d47a389199a3
Create Date: 2025-12-03 19:45:32.006029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2e9865e0059"
down_revision: Union[str, None] = "d47a389199a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidates", "work_experience")
    op.drop_column("candidates", "education")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidates",
        sa.Column("education", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "candidates",
        sa.Column("work_experience", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
