"""edit user model

Revision ID: 69c2378ffd89
Revises: 73ba232bd31a
Create Date: 2025-11-29 16:35:25.314608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69c2378ffd89"
down_revision: Union[str, None] = "73ba232bd31a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidate_profiles", "surname")
    op.drop_column("candidate_profiles", "patronymic")
    op.drop_column("candidate_profiles", "name")
    op.add_column("users", sa.Column("surname", sa.String(length=50), nullable=False))
    op.add_column("users", sa.Column("name", sa.String(length=50), nullable=False))
    op.add_column("users", sa.Column("patronymic", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "patronymic")
    op.drop_column("users", "name")
    op.drop_column("users", "surname")
    op.add_column(
        "candidate_profiles",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.add_column(
        "candidate_profiles",
        sa.Column(
            "patronymic",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "candidate_profiles",
        sa.Column(
            "surname",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
