"""cand id

Revision ID: 92e0dec4dfe7
Revises: d2e9865e0059
Create Date: 2025-12-03 20:20:40.325040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92e0dec4dfe7"
down_revision: Union[str, None] = "d2e9865e0059"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "experiences", sa.Column("candidate_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "experiences", "candidates", ["candidate_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "experiences", type_="foreignkey")
    op.drop_column("experiences", "candidate_id")
    # ### end Alembic commands ###
