"""unique phone

Revision ID: 0ec7ca4e72e5
Revises: 79b2ccc040ff
Create Date: 2025-11-30 17:21:51.883378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ec7ca4e72e5"
down_revision: Union[str, None] = "79b2ccc040ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "candidates", ["phone"])
    op.create_unique_constraint(None, "recruiters", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recruiters", type_="unique")
    op.drop_constraint(None, "candidates", type_="unique")
    # ### end Alembic commands ###
