"""patr nullable

Revision ID: be11ce804f8e
Revises: d8e57c1f8c01
Create Date: 2025-12-02 18:04:59.431471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be11ce804f8e"
down_revision: Union[str, None] = "d8e57c1f8c01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "patronymic",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "patronymic",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    # ### end Alembic commands ###
