"""fio user

Revision ID: d8e57c1f8c01
Revises: f4a2f1fc346e
Create Date: 2025-12-01 17:55:43.392842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8e57c1f8c01"
down_revision: Union[str, None] = "f4a2f1fc346e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidates", "patronymic")
    op.drop_column("candidates", "surname")
    op.drop_column("candidates", "name")
    op.drop_column("recruiters", "patronymic")
    op.drop_column("recruiters", "surname")
    op.drop_column("recruiters", "name")
    op.add_column(
        "users", sa.Column("surname", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "users", sa.Column("name", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "users", sa.Column("patronymic", sa.String(length=100), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "patronymic")
    op.drop_column("users", "name")
    op.drop_column("users", "surname")
    op.add_column(
        "recruiters",
        sa.Column(
            "name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "recruiters",
        sa.Column(
            "surname",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "recruiters",
        sa.Column(
            "patronymic",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "candidates",
        sa.Column(
            "name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "candidates",
        sa.Column(
            "surname",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "candidates",
        sa.Column(
            "patronymic",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
