"""recruiter phone

Revision ID: 006c93abecb0
Revises: 01001d2121fa
Create Date: 2025-11-30 15:08:20.060848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "006c93abecb0"
down_revision: Union[str, None] = "01001d2121fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recruiters", sa.Column("phone", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recruiters", "phone")
    # ### end Alembic commands ###
