"""user phone

Revision ID: f4a2f1fc346e
Revises: 0ec7ca4e72e5
Create Date: 2025-12-01 17:11:15.367617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4a2f1fc346e"
down_revision: Union[str, None] = "0ec7ca4e72e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("candidates_phone_key", "candidates", type_="unique")
    op.drop_column("candidates", "phone")
    op.drop_constraint("recruiters_phone_key", "recruiters", type_="unique")
    op.drop_column("recruiters", "phone")
    op.add_column("users", sa.Column("phone", sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, "users", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "phone")
    op.add_column(
        "recruiters",
        sa.Column("phone", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint("recruiters_phone_key", "recruiters", ["phone"])
    op.add_column(
        "candidates",
        sa.Column("phone", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint("candidates_phone_key", "candidates", ["phone"])
    # ### end Alembic commands ###
