"""edit pos field

Revision ID: 79b2ccc040ff
Revises: 006c93abecb0
Create Date: 2025-11-30 16:55:50.671000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79b2ccc040ff"
down_revision: Union[str, None] = "006c93abecb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recruiters",
        sa.Column("position", sa.String(length=100), nullable=False),
    )
    op.drop_column("recruiters", "postition")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recruiters",
        sa.Column(
            "postition",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("recruiters", "position")
    # ### end Alembic commands ###
