"""vacancy recruiter rel

Revision ID: b9f563b7b925
Revises: 14f79e862dfc
Create Date: 2025-12-09 16:55:47.387735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9f563b7b925"
down_revision: Union[str, None] = "14f79e862dfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vacancies", sa.Column("recruiter_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "vacancies", "recruiters", ["recruiter_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vacancies", type_="foreignkey")
    op.drop_column("vacancies", "recruiter_id")
    # ### end Alembic commands ###
