"""created educatuion & experience models

Revision ID: d47a389199a3
Revises: 05475e0d82c3
Create Date: 2025-12-03 19:43:51.859922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d47a389199a3"
down_revision: Union[str, None] = "05475e0d82c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiences",
        sa.Column("company", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "educations",
        sa.Column(
            "educational_institution_title",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=20), nullable=True),
        sa.Column("direction", sa.String(length=100), nullable=True),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("educations")
    op.drop_table("experiences")
    # ### end Alembic commands ###
