"""roles

Revision ID: 3b75fbf52f48
Revises: e29b06dba26c
Create Date: 2025-11-19 01:49:19.786299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b75fbf52f48"
down_revision: Union[str, None] = "e29b06dba26c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_active", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("permission_level", sa.Integer(), nullable=False)
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            postgresql.ENUM("ADMIN", "HR", "CANDIDATE", name="userrole"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "permission_level")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
