"""user ondelete

Revision ID: 39bd5d68a5c9
Revises: 0d33cae2a174
Create Date: 2025-11-20 21:41:27.468375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39bd5d68a5c9"
down_revision: Union[str, None] = "0d33cae2a174"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "candidate_profiles_user_id_fkey",
        "candidate_profiles",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "candidate_profiles",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "candidate_profiles", type_="foreignkey")
    op.create_foreign_key(
        "candidate_profiles_user_id_fkey",
        "candidate_profiles",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
