"""required fields

Revision ID: 0d33cae2a174
Revises: af9dd35a61e8
Create Date: 2025-11-20 21:08:54.388483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d33cae2a174"
down_revision: Union[str, None] = "af9dd35a61e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "candidate_profiles",
        "work_experience",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "candidate_profiles",
        "education",
        existing_type=sa.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "candidate_profiles",
        "education",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "candidate_profiles",
        "work_experience",
        existing_type=sa.TEXT(),
        nullable=False,
    )
    # ### end Alembic commands ###
