"""experience, birth date, education

Revision ID: 37e9a37009a8
Revises: 3b75fbf52f48
Create Date: 2025-11-20 20:27:48.086892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37e9a37009a8"
down_revision: Union[str, None] = "3b75fbf52f48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_profiles",
        sa.Column("birth_date", sa.DateTime(), nullable=False),
    )
    op.add_column(
        "candidate_profiles",
        sa.Column("work_experience", sa.Text(), nullable=False),
    )
    op.drop_column("candidate_profiles", "age")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_profiles",
        sa.Column("age", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("candidate_profiles", "work_experience")
    op.drop_column("candidate_profiles", "birth_date")
    # ### end Alembic commands ###
