"""uniqueconstraint text question id

Revision ID: b70c744a626e
Revises: cb36ed09a6fd
Create Date: 2025-12-13 01:47:56.894004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b70c744a626e"
down_revision: Union[str, None] = "cb36ed09a6fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "idx_unique_text_questionid", "answers", ["text", "question_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("idx_unique_text_questionid", "answers", type_="unique")
    # ### end Alembic commands ###
