"""vacancy model

Revision ID: 6dbeb18288e2
Revises: 27253808af8a
Create Date: 2025-12-05 15:48:14.505833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6dbeb18288e2"
down_revision: Union[str, None] = "27253808af8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancies",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("min_salary", sa.Integer(), nullable=True),
        sa.Column("max_salary", sa.Integer(), nullable=True),
        sa.Column(
            "salary_period",
            sa.Enum("MONTH", "YEAR", "HOUR", name="period"),
            nullable=True,
        ),
        sa.Column(
            "experience",
            sa.Enum(
                "NO_EXPERIENCE",
                "LESS_THAN_1",
                "FROM_1_TO_2",
                "FROM_3_TO_6",
                "MORE_THAN_6",
                name="workexperience",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "max_salary IS NULL OR max_salary >= 0",
            name="max_salary_non_negative",
        ),
        sa.CheckConstraint(
            "max_salary IS NULL OR max_salary >= min_salary",
            name="min_not_greater_than_max",
        ),
        sa.CheckConstraint("min_salary >= 0", name="min_salary_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vacancies")
    # ### end Alembic commands ###
