"""company in vacancy

Revision ID: 3118e8c6c20f
Revises: 6dbeb18288e2
Create Date: 2025-12-05 15:54:28.056696

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3118e8c6c20f"
down_revision: Union[str, None] = "6dbeb18288e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recruiters", "company")
    op.add_column(
        "vacancies",
        sa.Column("company", sa.String(length=100), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancies", "company")
    op.add_column(
        "recruiters",
        sa.Column(
            "company",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
