"""question skill assoc

Revision ID: cb36ed09a6fd
Revises: 0ea9b59c45d6
Create Date: 2025-12-12 00:37:37.624029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb36ed09a6fd"
down_revision: Union[str, None] = "0ea9b59c45d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("skill_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        "idx_unique_text_skillid", "questions", ["text", "skill_id"]
    )
    op.create_foreign_key(None, "questions", "skills", ["skill_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.drop_constraint("idx_unique_text_skillid", "questions", type_="unique")
    op.drop_column("questions", "skill_id")
    # ### end Alembic commands ###
