"""edit candidate model

Revision ID: da801df0736f
Revises: 69c2378ffd89
Create Date: 2025-11-29 16:36:49.934241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da801df0736f"
down_revision: Union[str, None] = "69c2378ffd89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidates",
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("work_experience", sa.Text(), nullable=True),
        sa.Column("education", sa.Text(), nullable=True),
        sa.Column("about_candidate", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.drop_table("candidate_profiles")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_profiles",
        sa.Column("birth_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("work_experience", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("education", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("about_candidate", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="candidate_profiles_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="candidate_profiles_pkey"),
        sa.UniqueConstraint("user_id", name="candidate_profiles_user_id_key"),
    )
    op.drop_table("candidates")
    # ### end Alembic commands ###
