name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports: [5433:5432]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Установка зависимостей python
      run: |
        cd app
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd auth
        python certs.py
    
    - name: Запуск базы данных
      run: |
        sleep 5
    
    - name: Запуск миграций
      run: |
        cd app/shared/
        alembic upgrade head
      env:
        TEST_DB_URL: postgresql+asyncpg://postgres:postgres@localhost:5433/test_db
    
    - name: Запуск тестов
      run: |
        cd app
        python -m pytest tests/ -v
      env:
        TEST_DB_URL: postgresql+asyncpg://postgres:postgres@localhost:5433/test_db